// The 53 posts that predate the app router.
//
// They are static HTML in public/blog/<slug>/index.html, exported by the old
// Astro build and copied verbatim into out/. Nothing here renders them; this
// file exists so /blog can list them, so the new posts can link to them, and so
// whoever owns the sitemap has one importable list instead of a directory scan.
//
// Their URLs carry a trailing slash because a directory of index.html files is
// what Cloudflare Pages serves that way, and their canonical tags already say
// so. New posts export as `<slug>.html` and carry no trailing slash. Do not
// "normalise" one to the other: the canonical and the served path have to agree,
// and they only agree per post.
//
// Titles and descriptions are lifted from each file's own <title>, meta
// description and articleSection, with one edit: em and en dashes are replaced,
// because this file is the copy the /blog index renders and the house rule is
// that a member never reads one. The originals inside public/blog still have
// them; that is a separate cleanup on files this router does not own.

export const LEGACY_POSTS = [
  {
    slug: "advanced-pelvic-floor-exercises",
    title: "Beyond Kegels: 5 Advanced Pelvic Floor Exercises for Core Strength",
    description: "Already nailed the basics? Level up with advanced, whole-core exercises that integrate pelvic floor endurance, power, and pressure control into real movement.",
    category: "Pelvic Floor Exercises",
    published: "2025-08-15",
    legacy: true,
  },
  {
    slug: "beginners-guide-to-healing-diastasis-recti",
    title: "A Beginner's Guide to Healing Diastasis Recti",
    description: "Struggling with a 'mummy tummy' or core weakness postpartum? Learn how to check for diastasis recti and the safe, effective exercises to heal your core.",
    category: "Core & Breathing",
    published: "2025-08-09",
    legacy: true,
  },
  {
    slug: "breathing-for-pelvic-floor-exercises",
    title: "The Role of Breathing in Pelvic Floor Exercises: The Diaphragm Connection",
    description: "Your breath is the engine of pelvic floor training. Master the diaphragm-pelvic floor ‘piston’ for better strength, fewer leaks, and a calmer nervous system.",
    category: "Pelvic Floor Exercises",
    published: "2025-08-15",
    legacy: true,
  },
  {
    slug: "c-section-recovery-scar-massage-core-plan",
    title: "C-Section Recovery Guide: Scar Massage, Core Rebuild, and a 12-Week Daily Plan",
    description: "Your step-by-step recovery after a cesarean birth. Learn when to start moving, how to reduce pain and swelling, safe core and pelvic floor reactivation, and exactly how to begin C-section scar massage once cleared.",
    category: "Postpartum Recovery",
    published: "2025-08-02",
    legacy: true,
  },
  {
    slug: "can-stress-and-anxiety-cause-pelvic-pain",
    title: "Can Stress and Anxiety Cause Pelvic Pain? The Mind-Body Connection",
    description: "Your pelvic pain might not be a purely physical issue. Learn how chronic stress and anxiety lead to pelvic floor tension and discover techniques to break the cycle.",
    category: "Pain & Relaxation",
    published: "2025-08-10",
    legacy: true,
  },
  {
    slug: "common-pelvic-floor-exercise-mistakes",
    title: "Common Mistakes in Pelvic Floor Exercises (And How to Fix Them)",
    description: "If Kegels haven’t worked, it’s not you, it’s the method. Avoid the top form, breathing, and programming errors that stall progress and learn fast fixes.",
    category: "Pelvic Floor Exercises",
    published: "2025-08-15",
    legacy: true,
  },
  {
    slug: "fast-vs-slow-twitch-pelvic-floor-how-to-train-both",
    title: "Fast vs. Slow-Twitch Pelvic Floor: How to Train Both for Leak Control, Support, and Sensation",
    description: "Your pelvic floor has fast- and slow-twitch fibers. Learn the science and a step-by-step plan to build all-day support and quick, reflexive protection for coughs, sneezes, lifting, and better sexual function.",
    category: "Anatomy & Science",
    published: "2025-08-02",
    legacy: true,
  },
  {
    slug: "gentle-stretches-to-relieve-pelvic-pain",
    title: "5 Gentle Stretches to Relieve Pelvic Pain and Tension",
    description: "Find immediate relief from pelvic pain and tightness with these 5 gentle, physical therapist-approved stretches. Perfect for beginners and safe for daily practice.",
    category: "Pain & Relaxation",
    published: "2025-08-11",
    legacy: true,
  },
  {
    slug: "guide-to-diaphragmatic-breathing-for-pelvic-floor",
    title: "The Ultimate Guide to Diaphragmatic Breathing for Pelvic Floor Health",
    description: "Unlock the secret to a stronger core and pelvic floor. Our guide to diaphragmatic breathing teaches you how to reduce leaks, ease pain, and build true stability. Learn the technique.",
    category: "Core & Breathing",
    published: "2025-08-05",
    legacy: true,
  },
  {
    slug: "guide-to-painful-intercourse-dyspareunia",
    title: "Painful Intercourse (Dyspareunia): A Guide to Understanding and Finding Relief",
    description: "Pain during sex is common, but it's not normal. Learn about the number one physical cause, a tight pelvic floor, and discover gentle, effective strategies to reclaim intimacy.",
    category: "Pain & Relaxation",
    published: "2025-08-12",
    legacy: true,
  },
  {
    slug: "guide-to-releasing-a-tight-pelvic-floor",
    title: "A Guide to Releasing a Tight (Hypertonic) Pelvic Floor",
    description: "Is pelvic pain, urgency, or painful intimacy affecting your life? Your pelvic floor might be too tight. Learn the signs and the best techniques for relaxation and release.",
    category: "Pain & Relaxation",
    published: "2025-08-06",
    legacy: true,
  },
  {
    slug: "how-to-do-kegels-correctly",
    title: "How to Do Kegels Correctly: A Step-by-Step Guide to Pelvic Floor Exercises",
    description: "Master the correct way to do pelvic floor exercises (Kegels). Learn how to find the right muscles, breathe properly, avoid common mistakes, and follow a proven routine from beginner to advanced.",
    category: "Pelvic Floor Exercises",
    published: "2025-08-15",
    legacy: true,
  },
  {
    slug: "how-to-stop-leaking-when-you-cough-sneeze",
    title: "How to Stop Leaking When You Cough or Sneeze (The Knack Method)",
    description: "Tired of embarrassing leaks when you cough, sneeze, or laugh? Learn 'The Knack,' a simple, life-changing technique recommended by physical therapists to stay dry and confident.",
    category: "Leakproof Control",
    published: "2025-08-01",
    legacy: true,
  },
  {
    slug: "how-your-posture-affects-your-pelvic-floor",
    title: "How Your Posture Affects Your Pelvic Floor (And How to Fix It)",
    description: "Slouching at your desk? That might be the real reason for your leaks or pelvic pain. Learn how simple postural changes can dramatically improve your pelvic floor function.",
    category: "Core & Breathing",
    published: "2025-08-07",
    legacy: true,
  },
  {
    slug: "hypertonic-vs-hypotonic-pelvic-floor-self-checks-treatment",
    title: "Hypertonic vs Hypotonic Pelvic Floor: Self-Checks, Symptoms, and What Actually Helps",
    description: "Are your pelvic floor muscles too tight or too weak? Learn the science of muscle tone, clear self-checks to tell the difference, and step-by-step plans for both hypertonic and hypotonic patterns.",
    category: "Anatomy & Science",
    published: "2025-08-02",
    legacy: true,
  },
  {
    slug: "kegels-for-men-erectile-function",
    title: "Men: Kegel Exercises for Erectile Function (Step-by-Step Plan)",
    description: "A clear, proven routine for men to use pelvic floor (Kegel) exercises to support erections and control. Learn exact cues, weekly progressions, and mistakes to avoid.",
    category: "For Men",
    published: "2025-08-02",
    legacy: true,
  },
  {
    slug: "last-longer-men-premature-ejaculation-training",
    title: "Men: Last Longer with Pelvic Floor Training (Premature Ejaculation Control)",
    description: "Last longer without pills. Learn the exact pelvic floor techniques, timed contractions, reverse releases, breath control, and start-stop practice, that help men overcome premature ejaculation and build reliable stamina.",
    category: "For Men",
    published: "2025-08-02",
    legacy: true,
  },
  {
    slug: "lift-weights-without-leaking",
    title: "Lift Weights Without Leaking: A Pelvic Floor-Safe Strength Training Guide",
    description: "Tired of leaks during squats, deadlifts, or classes? Use this PT-approved plan to brace better, pick the right exercises, and progress your strength, without stressing your pelvic floor.",
    category: "Fitness & Lifestyle",
    published: "2025-08-08",
    legacy: true,
  },
  {
    slug: "obturator-internus-hip-pelvic-floor-pain-release-guide",
    title: "Obturator Internus: The Hidden Hip Muscle Behind Pelvic Floor Pain, Symptoms, Self-Checks, and Safe Release",
    description: "Think your pelvic pain is ‘just tight pelvic floor’? The deep hip rotator obturator internus often drives sit-bone pain, painful sex, and tailbone pressure. Learn the anatomy, red flags, and a safe step-by-step release plan that actually lasts.",
    category: "Anatomy & Science",
    published: "2025-08-02",
    legacy: true,
  },
  {
    slug: "painful-sex-after-birth-how-to-heal",
    title: "Painful Sex After Birth: Why It Happens & How to Heal (Step-by-Step)",
    description: "Pain with sex after birth is common, and fixable. Learn the causes (tears, scars, hormones, pelvic floor tension) and a proven plan to restore comfort and desire.",
    category: "Postpartum Recovery",
    published: "2025-08-02",
    legacy: true,
  },
  {
    slug: "painful-sex-relief-dilator-guide",
    title: "Painful Sex Relief at Home: Pelvic Floor Relaxation & Dilator Guide",
    description: "A safe, step-by-step plan to ease penetration pain (dyspareunia/vaginismus) at home using breath, reverse Kegels, graded touch, and dilators, plus lube, positions, and when to see a pelvic PT.",
    category: "Sexual Wellness",
    published: "2025-08-08",
    legacy: true,
  },
  {
    slug: "painful-sex-relief-pelvic-floor-relaxation-plan",
    title: "Painful Sex? A Step-by-Step Pelvic Floor Relaxation Plan for Comfortable, Confident Intimacy",
    description: "Experiencing pain with penetration (dyspareunia) or tightness that makes sex uncomfortable? Follow this evidence-informed pelvic floor relaxation plan to reduce pain, increase arousal, and rebuild confidence.",
    category: "Sexual Wellness",
    published: "2025-08-06",
    legacy: true,
  },
  {
    slug: "pelvic-floor-anatomy-muscles-how-to-find-them",
    title: "Pelvic Floor Anatomy for Men & Women: Muscles, Map, and How to Find Them",
    description: "A clear, clinician-built guide to the pelvic floor muscles (levator ani, sphincters, diaphragm connection) and exactly how to locate, relax, and activate them, safely and correctly.",
    category: "Anatomy & Science",
    published: "2025-08-02",
    legacy: true,
  },
  {
    slug: "pelvic-floor-exercises-for-beginners",
    title: "Pelvic Floor Exercises for Beginners: Your First 7-Day Plan",
    description: "Start here. A gentle, foolproof 7-day program to find the right muscles, sync with your breath, and build a habit you’ll actually keep.",
    category: "Pelvic Floor Exercises",
    published: "2025-08-15",
    legacy: true,
  },
  {
    slug: "pelvic-floor-exercises-for-intimacy",
    title: "Can Pelvic Floor Exercises Improve Intimacy? The Science Explained",
    description: "Understand how pelvic floor training affects arousal, lubrication, erection quality, orgasm, and comfort, plus a step-by-step plan that blends relaxation with strength.",
    category: "Pelvic Floor Exercises",
    published: "2025-08-15",
    legacy: true,
  },
  {
    slug: "pelvic-floor-exercises-for-men",
    title: "Pelvic Floor Exercises for Men: A Complete Guide for Bladder Control and Performance",
    description: "Men can dramatically improve bladder control, reduce post-void dribbling, and enhance sexual function with correct pelvic floor training. Learn cues, progressions, and a 12-week plan.",
    category: "Pelvic Floor Exercises",
    published: "2025-08-15",
    legacy: true,
  },
  {
    slug: "pelvic-floor-exercises-for-prolapse",
    title: "Pelvic Floor Exercises for Prolapse: Gentle Routines for Support and Relief",
    description: "A calm, confidence-building plan for prolapse. Learn breath-led pressure management, supportive endurance work, and daily strategies that reduce heaviness and improve comfort.",
    category: "Pelvic Floor Exercises",
    published: "2025-08-15",
    legacy: true,
  },
  {
    slug: "pelvic-floor-safe-ab-workouts",
    title: "Pelvic Floor-Safe Ab Workouts: Planks, Crunches & Core Without Leaks",
    description: "Leaking, doming, or back pain during ab workouts? Use this PT-approved plan to train your core safely, planks, crunches, and more, without stressing your pelvic floor.",
    category: "Fitness & Lifestyle",
    published: "2025-08-02",
    legacy: true,
  },
  {
    slug: "perineal-massage-birth-prep-guide",
    title: "Perineal Massage & Birth Prep: A 10-Minute Daily Routine from 34 Weeks",
    description: "Reduce tearing risk, improve comfort, and prepare your pelvic floor for birth with this simple 10-minute perineal massage and relaxation plan starting at 34 weeks.",
    category: "Pregnancy Journey",
    published: "2025-08-02",
    legacy: true,
  },
  {
    slug: "perineal-tear-stitches-care-healing-timeline-postpartum",
    title: "Perineal Tear & Stitches Care: Exact Healing Timeline and Comfort Tips After Birth",
    description: "Tore during birth? Get a clear week-by-week healing timeline for stitches, pain relief tips, how to clean and sit, and when to call your provider.",
    category: "Postpartum Recovery",
    published: "2025-08-02",
    legacy: true,
  },
  {
    slug: "postpartum-bleeding-lochia-whats-normal-when-to-call-doctor",
    title: "Postpartum Bleeding (Lochia): What’s Normal vs When to Call Your Doctor",
    description: "Worried about postpartum bleeding? Learn exactly what lochia should look like week by week, what’s not normal, and when to seek medical care.",
    category: "Postpartum Recovery",
    published: "2025-08-02",
    legacy: true,
  },
  {
    slug: "postpartum-constipation-relief-fast-safe",
    title: "Postpartum Constipation Relief: Fast, Safe Ways to Go Without Straining",
    description: "Constipated after birth? Get rapid relief with stool-softening foods, positions that work, gentle techniques that protect stitches, and a 3-day reset plan.",
    category: "Postpartum Recovery",
    published: "2025-08-02",
    legacy: true,
  },
  {
    slug: "postpartum-diastasis-recti-8-week-plan",
    title: "Postpartum Diastasis Recti: Flatten Your Belly Safely (8-Week Plan, No Crunches)",
    description: "A clinically informed, step-by-step program to close the gap, restore core tension, and flatten the postpartum belly, without crunches or risky moves. Includes self-test, daily habits, and an 8-week progression.",
    category: "Postpartum Recovery",
    published: "2025-08-02",
    legacy: true,
  },
  {
    slug: "postpartum-hemorrhoids-relief-at-home",
    title: "Postpartum Hemorrhoids: Fast Relief at Home (Positions, Products, and a 7-Day Plan)",
    description: "Burning or itching after birth? Get rapid, safe relief from postpartum hemorrhoids with sitz baths, smart toilet posture, gentle movement, and a simple weeklong plan.",
    category: "Postpartum Recovery",
    published: "2025-08-02",
    legacy: true,
  },
  {
    slug: "postpartum-pelvic-floor-exercises",
    title: "Postpartum Pelvic Floor Exercises: A 12-Week Healing and Recovery Plan",
    description: "Your complete, trimester-style roadmap for the fourth trimester. Reconnect, rebuild, and return to the movement you love with a safe, progressive 12-week pelvic floor plan.",
    category: "Pelvic Floor Exercises",
    published: "2025-08-15",
    legacy: true,
  },
  {
    slug: "postpartum-prolapse-recovery-without-surgery-12-week-plan",
    title: "Postpartum Prolapse Recovery: 12-Week Non-Surgical Plan (Safe, Step-by-Step)",
    description: "A clear, non-surgical 12-week plan to reduce prolapse symptoms after birth, covering breath, pressure control, pelvic floor training, and daily habit fixes. Includes red flags, timelines, and progress tests.",
    category: "Postpartum Recovery",
    published: "2025-08-02",
    legacy: true,
  },
  {
    slug: "postpartum-return-to-running-checklist-8-week-plan",
    title: "When Can I Start Running Postpartum? Safe Return-to-Run Checklist + 8-Week Plan",
    description: "Ready to run again after birth? Use this evidence-informed readiness checklist and a phased 8-week plan to return to running safely, without leaks, pain, or setbacks.",
    category: "Postpartum Recovery",
    published: "2025-08-06",
    legacy: true,
  },
  {
    slug: "postpartum-tailbone-pain-coccydynia-relief",
    title: "Postpartum Tailbone Pain (Coccydynia): Causes, Relief at Home, and When to Seek Help",
    description: "Hurting when you sit after birth? Learn why postpartum tailbone pain happens, the best sitting positions and cushions, gentle exercises, and when to get medical help.",
    category: "Postpartum Recovery",
    published: "2025-08-02",
    legacy: true,
  },
  {
    slug: "prepare-pelvic-floor-for-birth-6-week-plan",
    title: "Prepare Your Pelvic Floor for Birth: A 6-Week Plan (Weeks 34 to 40)",
    description: "High-impact, week-by-week preparation to reduce tearing risk, improve pushing efficiency, and speed postpartum recovery, using breath, reverse Kegels, smart positions, and perineal massage.",
    category: "Pregnancy Journey",
    published: "2025-08-02",
    legacy: true,
  },
  {
    slug: "relieve-pregnancy-pelvic-pain-spd-pgp",
    title: "Relieve Pregnancy Pelvic Pain (SPD/PGP): Daily Plan, Positions, and What Actually Helps",
    description: "Pelvic girdle pain (SPD/PGP) in pregnancy is common, but fixable. Use this step-by-step plan to reduce pain now, protect your pelvis, and move with confidence through birth.",
    category: "Pregnancy Journey",
    published: "2025-08-02",
    legacy: true,
  },
  {
    slug: "safe-pelvic-floor-exercises-for-pregnancy",
    title: "Safe Pelvic Floor Exercises for Every Stage of Pregnancy",
    description: "A trimester-by-trimester guide to safe pelvic floor training in pregnancy. Learn the right cues, how to balance strength with relaxation, and how to prepare for birth and postpartum recovery.",
    category: "Pelvic Floor Exercises",
    published: "2025-08-15",
    legacy: true,
  },
  {
    slug: "spd-pregnancy-pain-relief-sleep-positions",
    title: "Pregnancy SPD Relief: Sleep Positions, Daily Fixes, and a 10-Minute Plan",
    description: "Pelvic pain in pregnancy (SPD or symphysis pubis dysfunction) can make walking, turning in bed, or getting dressed painful. Use these sleep positions, daily movement tweaks, and a 10-minute routine to feel better fast.",
    category: "Pregnancy Journey",
    published: "2025-08-02",
    legacy: true,
  },
  {
    slug: "stop-dribbling-after-you-pee-men",
    title: "Men: Stop Dribbling After You Pee (Post-Void Dribble Fix)",
    description: "Still leaking a few drops after you finish peeing? Learn the real causes of post-void dribble in men and the exact techniques, body positioning, urethral milking, and breath-timed pelvic floor training, to stop it fast.",
    category: "For Men",
    published: "2025-08-02",
    legacy: true,
  },
  {
    slug: "stop-leaking-after-prostate-surgery-men",
    title: "Men: Stop Leaking After Prostate Surgery (Kegel Plan, Timing & Recovery)",
    description: "Still leaking after prostate surgery? This men’s guide shows you exactly how to find the right pelvic floor muscles, breathe correctly, and follow a 6-week progression to regain bladder control.",
    category: "For Men",
    published: "2025-08-02",
    legacy: true,
  },
  {
    slug: "stop-leaking-during-hiit-and-jumping",
    title: "Stop Leaking During HIIT, Jumping Jacks & Jump Rope: A PT-Approved Plan",
    description: "Leaks in HIIT classes or during jumping jacks, box jumps, or jump rope? Use this pelvic floor-smart plan to fix timing, manage pressure, and keep your cardio high, without the leaks.",
    category: "Fitness & Lifestyle",
    published: "2025-08-09",
    legacy: true,
  },
  {
    slug: "stop-leaking-during-jumping-jacks-hiit",
    title: "Stop Leaking During Jumping Jacks, Jump Rope & HIIT (The Impact Plan)",
    description: "Leaks during jumping or HIIT? Use this PT-designed progression to train high-impact, jumping jacks, jump rope, burpees, without accidents. Breath, timing, and a 4-week plan.",
    category: "Fitness & Lifestyle",
    published: "2025-08-02",
    legacy: true,
  },
  {
    slug: "stronger-orgasms-pelvic-floor-exercises",
    title: "Stronger Orgasms with Pelvic Floor Training: A Safe, 4-Week Home Plan",
    description: "Looking for more sensation and stronger orgasms? Use this step-by-step pelvic floor program, breath, reverse Kegels, coordination, and strength, to boost arousal and climax safely at home.",
    category: "Sexual Wellness",
    published: "2025-08-08",
    legacy: true,
  },
  {
    slug: "top-5-foods-that-irritate-your-bladder",
    title: "Top 5 Foods and Drinks That Can Irritate Your Bladder",
    description: "Struggling with bladder urgency or frequency? Learn about the top 5 common foods and drinks that can act as bladder irritants and how to identify your personal triggers.",
    category: "Leakproof Control",
    published: "2025-08-04",
    legacy: true,
  },
  {
    slug: "ultimate-guide-to-pelvic-floor-exercises",
    title: "The Ultimate Guide to Pelvic Floor Exercises: For Beginners to Advanced",
    description: "The definitive, evidence-based guide to pelvic floor exercises (Kegels). Learn how to find the right muscles, perform exercises correctly, and build a routine for lifelong core health.",
    category: "Pelvic Floor Exercises",
    published: "2025-08-15",
    legacy: true,
  },
  {
    slug: "understanding-urge-vs-stress-incontinence",
    title: "Urge vs. Stress Incontinence: What's the Difference?",
    description: "Not all leaks are the same. Understand the key differences between urge incontinence (overactive bladder) and stress incontinence (leaks from pressure) to find the right strategies for staying dry and in control.",
    category: "Leakproof Control",
    published: "2025-08-03",
    legacy: true,
  },
  {
    slug: "vaginismus-home-treatment-plan",
    title: "Vaginismus Home Treatment Plan: A Gentle, Step-By-Step Path to Comfortable Penetration",
    description: "Struggling with vaginismus or penetration pain? Follow this clinic-style home plan to relax a tight pelvic floor, use dilators safely, and rebuild comfort and confidence, at your pace.",
    category: "Sexual Wellness",
    published: "2025-08-07",
    legacy: true,
  },
  {
    slug: "what-is-the-transverse-abdominis",
    title: "What is the Transverse Abdominis and How Do You Activate It?",
    description: "Often called your body's 'natural corset,' the Transverse Abdominis (TVA) is the key to core stability. Learn why it matters and how to activate it correctly.",
    category: "Core & Breathing",
    published: "2025-08-08",
    legacy: true,
  },
  {
    slug: "why-am-i-still-leaking-after-kegels",
    title: "Why Am I Still Leaking After Doing Kegels for Weeks?",
    description: "Feeling frustrated that your Kegels aren't stopping leaks? Discover the 5 common reasons why they might not be working and how to fix your technique for good.",
    category: "Leakproof Control",
    published: "2025-08-02",
    legacy: true,
  },
];

/** Legacy posts live at /blog/<slug>/ with the trailing slash. */
export function legacyHref(slug) {
  return `/blog/${slug}/`;
}
